version: "2.28"

services: 
  first-micro4delphi-usuariosapp:
    image: micro4delphi/usuariosapp
    container_name: first-micro4delphi-usuariosapp
    ports: 
      - "9011:9000"
    environment:
      - PONG=1

  second-micro4delphi-usuariosapp:
    image: micro4delphi/usuariosapp
    container_name: second-micro4delphi-usuariosapp
    ports: 
      - "9012:9000"
    environment:
      - PONG=2

  micro4delphiusuariosnginx-server:
    image: micro4delphi/usuariosnginx
    container_name: micro4delphinginx-usuarioscompose
    ports: 
      - "8081:80"
    depends_on: 
      - first-micro4delphi-usuariosapp
      - second-micro4delphi-usuariosapp

      